% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Jan-2025 15:02:24
%  MATLAB version: 24.2.0.2740171 (R2024b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

LIC = cell(9, 1);
LIC{1,1} = [];
LIC{2,1} = [];
LIC{3,1} = [];
LIC{4,1} = [];
LIC{5,1} = [];
LIC{6,1} = [];
LIC{7,1} = [];
LIC{8,1} = [];
LIC{9,1} = [];

calu = 1;

calv = 1;

calxy = 1;

correlation_map = cell(9, 1);
correlation_map{1,1} = [];
correlation_map{2,1} = [];
correlation_map{3,1} = [];
correlation_map{4,1} = [];
correlation_map{5,1} = [];
correlation_map{6,1} = [];
correlation_map{7,1} = [];
correlation_map{8,1} = [];
correlation_map{9,1} = [];

correlation_matrices = cell(1, 9);
correlation_matrices{1} = [];
correlation_matrices{2} = [];
correlation_matrices{3} = [];
correlation_matrices{4} = [];
correlation_matrices{5} = [];
correlation_matrices{6} = [];
correlation_matrices{7} = [];
correlation_matrices{8} = [];
correlation_matrices{9} = [];

divergence = cell(9, 1);
divergence{1,1} = [];
divergence{2,1} = [];
divergence{3,1} = [];
divergence{4,1} = [];
divergence{5,1} = [];
divergence{6,1} = [];
divergence{7,1} = [];
divergence{8,1} = [];
divergence{9,1} = [];

shear_rate = cell(9, 1);
shear_rate{1,1} = [];
shear_rate{2,1} = [];
shear_rate{3,1} = [];
shear_rate{4,1} = [];
shear_rate{5,1} = [];
shear_rate{6,1} = [];
shear_rate{7,1} = [];
shear_rate{8,1} = [];
shear_rate{9,1} = [];

strain_rate = cell(9, 1);
strain_rate{1,1} = [];
strain_rate{2,1} = [];
strain_rate{3,1} = [];
strain_rate{4,1} = [];
strain_rate{5,1} = [];
strain_rate{6,1} = [];
strain_rate{7,1} = [];
strain_rate{8,1} = [];
strain_rate{9,1} = [];

typevector_filtered = cell(9, 1);
typevector_filtered{1,1} = [];
typevector_filtered{2,1} = [];
typevector_filtered{3,1} = [];
typevector_filtered{4,1} = [];
typevector_filtered{5,1} = [];
typevector_filtered{6,1} = [];
typevector_filtered{7,1} = [];
typevector_filtered{8,1} = [];
typevector_filtered{9,1} = [];

typevector_original = saveVarsMat.typevector_original; % <9x1 cell> too many elements at typevector_original{1,1}

u_component = cell(9, 1);
u_component{1,1} = [];
u_component{2,1} = [];
u_component{3,1} = [];
u_component{4,1} = [];
u_component{5,1} = [];
u_component{6,1} = [];
u_component{7,1} = [];
u_component{8,1} = [];
u_component{9,1} = [];

u_filtered = cell(9, 1);
u_filtered{1,1} = [];
u_filtered{2,1} = [];
u_filtered{3,1} = [];
u_filtered{4,1} = [];
u_filtered{5,1} = [];
u_filtered{6,1} = [];
u_filtered{7,1} = [];
u_filtered{8,1} = [];
u_filtered{9,1} = [];

u_original = saveVarsMat.u_original; % <9x1 cell> too many elements at u_original{1,1}

u_smoothed = cell(9, 1);
u_smoothed{1,1} = [];
u_smoothed{2,1} = [];
u_smoothed{3,1} = [];
u_smoothed{4,1} = [];
u_smoothed{5,1} = [];
u_smoothed{6,1} = [];
u_smoothed{7,1} = [];
u_smoothed{8,1} = [];
u_smoothed{9,1} = [];

units = '[px] respectively [px/frame]';

v_component = cell(9, 1);
v_component{1,1} = [];
v_component{2,1} = [];
v_component{3,1} = [];
v_component{4,1} = [];
v_component{5,1} = [];
v_component{6,1} = [];
v_component{7,1} = [];
v_component{8,1} = [];
v_component{9,1} = [];

v_filtered = cell(9, 1);
v_filtered{1,1} = [];
v_filtered{2,1} = [];
v_filtered{3,1} = [];
v_filtered{4,1} = [];
v_filtered{5,1} = [];
v_filtered{6,1} = [];
v_filtered{7,1} = [];
v_filtered{8,1} = [];
v_filtered{9,1} = [];

v_original = saveVarsMat.v_original; % <9x1 cell> too many elements at v_original{1,1}

v_smoothed = cell(9, 1);
v_smoothed{1,1} = [];
v_smoothed{2,1} = [];
v_smoothed{3,1} = [];
v_smoothed{4,1} = [];
v_smoothed{5,1} = [];
v_smoothed{6,1} = [];
v_smoothed{7,1} = [];
v_smoothed{8,1} = [];
v_smoothed{9,1} = [];

vectorangle = cell(9, 1);
vectorangle{1,1} = [];
vectorangle{2,1} = [];
vectorangle{3,1} = [];
vectorangle{4,1} = [];
vectorangle{5,1} = [];
vectorangle{6,1} = [];
vectorangle{7,1} = [];
vectorangle{8,1} = [];
vectorangle{9,1} = [];

velocity_magnitude = cell(9, 1);
velocity_magnitude{1,1} = [];
velocity_magnitude{2,1} = [];
velocity_magnitude{3,1} = [];
velocity_magnitude{4,1} = [];
velocity_magnitude{5,1} = [];
velocity_magnitude{6,1} = [];
velocity_magnitude{7,1} = [];
velocity_magnitude{8,1} = [];
velocity_magnitude{9,1} = [];

vortex_locator = cell(9, 1);
vortex_locator{1,1} = [];
vortex_locator{2,1} = [];
vortex_locator{3,1} = [];
vortex_locator{4,1} = [];
vortex_locator{5,1} = [];
vortex_locator{6,1} = [];
vortex_locator{7,1} = [];
vortex_locator{8,1} = [];
vortex_locator{9,1} = [];

vorticity = cell(9, 1);
vorticity{1,1} = [];
vorticity{2,1} = [];
vorticity{3,1} = [];
vorticity{4,1} = [];
vorticity{5,1} = [];
vorticity{6,1} = [];
vorticity{7,1} = [];
vorticity{8,1} = [];
vorticity{9,1} = [];

x = saveVarsMat.x; % <9x1 cell> too many elements at x{1,1}

y = saveVarsMat.y; % <9x1 cell> too many elements at y{1,1}

clear saveVarsMat;
